import pymongo
import keras
import random
from keras.utils import Sequence
from keras.utils.np_utils import to_categorical
from keras.preprocessing.image import ImageDataGenerator
from keras.models import model_from_json
from PIL import Image
import numpy as np
import pydash


def trainer(params):

    model = model_from_json(params.architecture)

    model.compile(loss=params.config.loss,
                  optimizer=params.config.optimiser,
                  metrics=params.config.metrics)

    # Fit the model on the batches generated by datagen.flow().
    model.fit_generator(datagen.flow(x_train, y_train, batch_size=batch_size),
                        epochs=epochs,
                        validation_data=(x_test, y_test),
                        workers=4)

    model.save()

    return 'damn'
